version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: gophkeeper-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gophkeeper
    ports:
      - "5432:5432"
    volumes:
      - gophkeeper_postgres_data:/var/lib/postgresql/data


volumes:
  gophkeeper_postgres_data:
