// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: gophkeeper/v1/gophkeeper.proto

package gophkeeperv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	KdfSalt       []byte                 `protobuf:"bytes,3,opt,name=kdf_salt,json=kdfSalt,proto3" json:"kdf_salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetKdfSalt() []byte {
	if x != nil {
		return x.KdfSalt
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	KdfSalt       []byte                 `protobuf:"bytes,4,opt,name=kdf_salt,json=kdfSalt,proto3" json:"kdf_salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AuthResponse) GetKdfSalt() []byte {
	if x != nil {
		return x.KdfSalt
	}
	return nil
}

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *CreateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateItemRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *CreateItemRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type UpdateItemRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpectedRevision int64                  `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	Nonce            []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Ciphertext       []byte                 `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateItemRequest) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *UpdateItemRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *UpdateItemRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type DeleteItemRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpectedRevision int64                  `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteItemRequest) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *GetItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListItemsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeDeleted bool                   `protobuf:"varint,1,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *ListItemsRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type SyncRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AfterSyncVersion uint64                 `protobuf:"varint,1,opt,name=after_sync_version,json=afterSyncVersion,proto3" json:"after_sync_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{8}
}

func (x *SyncRequest) GetAfterSyncVersion() uint64 {
	if x != nil {
		return x.AfterSyncVersion
	}
	return 0
}

type ItemHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Revision      int64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	SyncVersion   uint64                 `protobuf:"varint,3,opt,name=sync_version,json=syncVersion,proto3" json:"sync_version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemHeader) Reset() {
	*x = ItemHeader{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemHeader) ProtoMessage() {}

func (x *ItemHeader) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemHeader.ProtoReflect.Descriptor instead.
func (*ItemHeader) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{9}
}

func (x *ItemHeader) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemHeader) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ItemHeader) GetSyncVersion() uint64 {
	if x != nil {
		return x.SyncVersion
	}
	return 0
}

func (x *ItemHeader) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ItemHeader) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ItemHeader) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type EncryptedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ItemHeader            `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedItem) Reset() {
	*x = EncryptedItem{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedItem) ProtoMessage() {}

func (x *EncryptedItem) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedItem.ProtoReflect.Descriptor instead.
func (*EncryptedItem) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{10}
}

func (x *EncryptedItem) GetHeader() *ItemHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *EncryptedItem) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedItem) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type DeleteItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ItemHeader            `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteItemResponse) GetHeader() *ItemHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*EncryptedItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{12}
}

func (x *ListItemsResponse) GetItems() []*EncryptedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SyncResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Items              []*EncryptedItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	CurrentSyncVersion uint64                 `protobuf:"varint,2,opt,name=current_sync_version,json=currentSyncVersion,proto3" json:"current_sync_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{13}
}

func (x *SyncResponse) GetItems() []*EncryptedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SyncResponse) GetCurrentSyncVersion() uint64 {
	if x != nil {
		return x.CurrentSyncVersion
	}
	return 0
}

var File_gophkeeper_v1_gophkeeper_proto protoreflect.FileDescriptor

const file_gophkeeper_v1_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x1egophkeeper/v1/gophkeeper.proto\x12\rgophkeeper.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xc3\x01\n" +
	"\x0fRegisterRequest\x12)\n" +
	"\x05login\x18\x01 \x01(\tB\x13\x92A\x102\vUser login.\x80\x01\x03R\x05login\x12=\n" +
	"\bpassword\x18\x02 \x01(\tB!\x92A\x1e2\x0eUser password.\x80\x01\b\xa2\x02\bpasswordR\bpassword\x12F\n" +
	"\bkdf_salt\x18\x03 \x01(\fB+\x92A(2\x1fBase64-encoded client KDF salt.\xa2\x02\x04byteR\akdfSalt\"r\n" +
	"\fLoginRequest\x12&\n" +
	"\x05login\x18\x01 \x01(\tB\x10\x92A\r2\vUser login.R\x05login\x12:\n" +
	"\bpassword\x18\x02 \x01(\tB\x1e\x92A\x1b2\x0eUser password.\xa2\x02\bpasswordR\bpassword\"\x84\x02\n" +
	"\fAuthResponse\x126\n" +
	"\auser_id\x18\x01 \x01(\tB\x1d\x92A\x1a2\x18Authenticated user UUID.R\x06userId\x129\n" +
	"\faccess_token\x18\x02 \x01(\tB\x16\x92A\x132\x11JWT access token.R\vaccessToken\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12F\n" +
	"\bkdf_salt\x18\x04 \x01(\fB+\x92A(2\x1fBase64-encoded client KDF salt.\xa2\x02\x04byteR\akdfSalt\"\xe5\x01\n" +
	"\x11CreateItemRequest\x129\n" +
	"\x02id\x18\x01 \x01(\tB)\x92A&2$Optional client-generated item UUID.R\x02id\x12?\n" +
	"\x05nonce\x18\x02 \x01(\fB)\x92A&2\x1dBase64-encoded AES-GCM nonce.\xa2\x02\x04byteR\x05nonce\x12T\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\fB4\x92A12(Base64-encoded encrypted client payload.\xa2\x02\x04byteR\n" +
	"ciphertext\"\xc5\x02\n" +
	"\x11UpdateItemRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\tB\x15\x92A\x122\x10Vault item UUID.R\x02id\x12r\n" +
	"\x11expected_revision\x18\x02 \x01(\x03BE\x92AB27Optimistic concurrency revision expected by the client.i\x00\x00\x00\x00\x00\x00\xf0?R\x10expectedRevision\x12?\n" +
	"\x05nonce\x18\x03 \x01(\fB)\x92A&2\x1dBase64-encoded AES-GCM nonce.\xa2\x02\x04byteR\x05nonce\x12T\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fB4\x92A12(Base64-encoded encrypted client payload.\xa2\x02\x04byteR\n" +
	"ciphertext\"\xae\x01\n" +
	"\x11DeleteItemRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\tB\x15\x92A\x122\x10Vault item UUID.R\x02id\x12r\n" +
	"\x11expected_revision\x18\x02 \x01(\x03BE\x92AB27Optimistic concurrency revision expected by the client.i\x00\x00\x00\x00\x00\x00\xf0?R\x10expectedRevision\"7\n" +
	"\x0eGetItemRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\tB\x15\x92A\x122\x10Vault item UUID.R\x02id\"n\n" +
	"\x10ListItemsRequest\x12Z\n" +
	"\x0finclude_deleted\x18\x01 \x01(\bB1\x92A.2,When true, deletion tombstones are returned.R\x0eincludeDeleted\"|\n" +
	"\vSyncRequest\x12m\n" +
	"\x12after_sync_version\x18\x01 \x01(\x04B?\x92A<2:Return changes with sync_version greater than this cursor.R\x10afterSyncVersion\"\xec\x02\n" +
	"\n" +
	"ItemHeader\x12%\n" +
	"\x02id\x18\x01 \x01(\tB\x15\x92A\x122\x10Vault item UUID.R\x02id\x12A\n" +
	"\brevision\x18\x02 \x01(\x03B%\x92A\"2 Optimistic concurrency revision.R\brevision\x12C\n" +
	"\fsync_version\x18\x03 \x01(\x04B \x92A\x1d2\x1bMonotonic user sync cursor.R\vsyncVersion\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\x85\x02\n" +
	"\rEncryptedItem\x121\n" +
	"\x06header\x18\x01 \x01(\v2\x19.gophkeeper.v1.ItemHeaderR\x06header\x12U\n" +
	"\x05nonce\x18\x02 \x01(\fB?\x92A<23Base64-encoded AES-GCM nonce. Empty for tombstones.\xa2\x02\x04byteR\x05nonce\x12j\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\fBJ\x92AG2>Base64-encoded encrypted client payload. Empty for tombstones.\xa2\x02\x04byteR\n" +
	"ciphertext\"G\n" +
	"\x12DeleteItemResponse\x121\n" +
	"\x06header\x18\x01 \x01(\v2\x19.gophkeeper.v1.ItemHeaderR\x06header\"G\n" +
	"\x11ListItemsResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.gophkeeper.v1.EncryptedItemR\x05items\"\x9e\x01\n" +
	"\fSyncResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.gophkeeper.v1.EncryptedItemR\x05items\x12Z\n" +
	"\x14current_sync_version\x18\x02 \x01(\x04B(\x92A%2#Current monotonic user sync cursor.R\x12currentSyncVersion2\xce\x03\n" +
	"\vAuthService\x12\xe0\x01\n" +
	"\bRegister\x12\x1e.gophkeeper.v1.RegisterRequest\x1a\x1b.gophkeeper.v1.AuthResponse\"\x96\x01\x92Aw\x12\x13Register a new user*\x14AuthService_Registerj\x1b\n" +
	"\rx-grpc-method\x12\n" +
	"\x1a\bRegisterj-\n" +
	"\x0ex-grpc-service\x12\x1b\x1a\x19gophkeeper.v1.AuthService\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/auth/register\x12\xdb\x01\n" +
	"\x05Login\x12\x1b.gophkeeper.v1.LoginRequest\x1a\x1b.gophkeeper.v1.AuthResponse\"\x97\x01\x92A{\x12\x1dAuthenticate an existing user*\x11AuthService_Loginj\x18\n" +
	"\rx-grpc-method\x12\a\x1a\x05Loginj-\n" +
	"\x0ex-grpc-service\x12\x1b\x1a\x19gophkeeper.v1.AuthService\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login2\xaa\f\n" +
	"\fVaultService\x12\x85\x02\n" +
	"\n" +
	"CreateItem\x12 .gophkeeper.v1.CreateItemRequest\x1a\x19.gophkeeper.v1.ItemHeader\"\xb9\x01\x92A\xa1\x01\x12%Create an opaque encrypted vault item*\x17VaultService_CreateItemb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00j\x1d\n" +
	"\rx-grpc-method\x12\f\x1a\n" +
	"CreateItemj.\n" +
	"\x0ex-grpc-service\x12\x1c\x1a\x1agophkeeper.v1.VaultService\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/items\x12\x8a\x02\n" +
	"\n" +
	"UpdateItem\x12 .gophkeeper.v1.UpdateItemRequest\x1a\x19.gophkeeper.v1.ItemHeader\"\xbe\x01\x92A\xa1\x01\x12%Update an opaque encrypted vault item*\x17VaultService_UpdateItemb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00j\x1d\n" +
	"\rx-grpc-method\x12\f\x1a\n" +
	"UpdateItemj.\n" +
	"\x0ex-grpc-service\x12\x1c\x1a\x1agophkeeper.v1.VaultService\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/items/{id}\x12\x8f\x02\n" +
	"\n" +
	"DeleteItem\x12 .gophkeeper.v1.DeleteItemRequest\x1a!.gophkeeper.v1.DeleteItemResponse\"\xbb\x01\x92A\xa1\x01\x12%Delete an opaque encrypted vault item*\x17VaultService_DeleteItemb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00j\x1d\n" +
	"\rx-grpc-method\x12\f\x1a\n" +
	"DeleteItemj.\n" +
	"\x0ex-grpc-service\x12\x1c\x1a\x1agophkeeper.v1.VaultService\x82\xd3\xe4\x93\x02\x10*\x0e/v1/items/{id}\x12\xfc\x01\n" +
	"\aGetItem\x12\x1d.gophkeeper.v1.GetItemRequest\x1a\x1c.gophkeeper.v1.EncryptedItem\"\xb3\x01\x92A\x99\x01\x12#Get one opaque encrypted vault item*\x14VaultService_GetItemb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00j\x1a\n" +
	"\rx-grpc-method\x12\t\x1a\aGetItemj.\n" +
	"\x0ex-grpc-service\x12\x1c\x1a\x1agophkeeper.v1.VaultService\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/items/{id}\x12\x81\x02\n" +
	"\tListItems\x12\x1f.gophkeeper.v1.ListItemsRequest\x1a .gophkeeper.v1.ListItemsResponse\"\xb0\x01\x92A\x9b\x01\x12!List opaque encrypted vault items*\x16VaultService_ListItemsb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00j\x1c\n" +
	"\rx-grpc-method\x12\v\x1a\tListItemsj.\n" +
	"\x0ex-grpc-service\x12\x1c\x1a\x1agophkeeper.v1.VaultService\x82\xd3\xe4\x93\x02\v\x12\t/v1/items\x12\xef\x01\n" +
	"\x04Sync\x12\x1a.gophkeeper.v1.SyncRequest\x1a\x1b.gophkeeper.v1.SyncResponse\"\xad\x01\x92A\x99\x01\x12)Synchronize opaque encrypted item changes*\x11VaultService_Syncb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00j\x17\n" +
	"\rx-grpc-method\x12\x06\x1a\x04Syncj.\n" +
	"\x0ex-grpc-service\x12\x1c\x1a\x1agophkeeper.v1.VaultService\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/syncB\xa0\x04\x92A\xc8\x03\x12\xdb\x01\n" +
	"\x0eGophKeeper API\x12\xc1\x01Swagger description generated from the GophKeeper gRPC proto contract. The production transport is gRPC; HTTP paths document the equivalent JSON mapping. Byte fields are base64-encoded strings.2\x051.0.0*\x02\x01\x022\x10application/json:\x10application/jsonZQ\n" +
	"O\n" +
	"\n" +
	"BearerAuth\x12A\b\x02\x12,JWT access token in the form: Bearer <token>\x1a\rAuthorization \x02j7\n" +
	"\vAuthService\x12(Registration and authentication methods.j4\n" +
	"\fVaultService\x12$Opaque encrypted vault item methods.ZRgithub.com/oilyin/gophkeeper/internal/transport/grpc/pb/gophkeeper/v1;gophkeeperv1b\x06proto3"

var (
	file_gophkeeper_v1_gophkeeper_proto_rawDescOnce sync.Once
	file_gophkeeper_v1_gophkeeper_proto_rawDescData []byte
)

func file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP() []byte {
	file_gophkeeper_v1_gophkeeper_proto_rawDescOnce.Do(func() {
		file_gophkeeper_v1_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_gophkeeper_proto_rawDesc), len(file_gophkeeper_v1_gophkeeper_proto_rawDesc)))
	})
	return file_gophkeeper_v1_gophkeeper_proto_rawDescData
}

var file_gophkeeper_v1_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_gophkeeper_v1_gophkeeper_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: gophkeeper.v1.RegisterRequest
	(*LoginRequest)(nil),          // 1: gophkeeper.v1.LoginRequest
	(*AuthResponse)(nil),          // 2: gophkeeper.v1.AuthResponse
	(*CreateItemRequest)(nil),     // 3: gophkeeper.v1.CreateItemRequest
	(*UpdateItemRequest)(nil),     // 4: gophkeeper.v1.UpdateItemRequest
	(*DeleteItemRequest)(nil),     // 5: gophkeeper.v1.DeleteItemRequest
	(*GetItemRequest)(nil),        // 6: gophkeeper.v1.GetItemRequest
	(*ListItemsRequest)(nil),      // 7: gophkeeper.v1.ListItemsRequest
	(*SyncRequest)(nil),           // 8: gophkeeper.v1.SyncRequest
	(*ItemHeader)(nil),            // 9: gophkeeper.v1.ItemHeader
	(*EncryptedItem)(nil),         // 10: gophkeeper.v1.EncryptedItem
	(*DeleteItemResponse)(nil),    // 11: gophkeeper.v1.DeleteItemResponse
	(*ListItemsResponse)(nil),     // 12: gophkeeper.v1.ListItemsResponse
	(*SyncResponse)(nil),          // 13: gophkeeper.v1.SyncResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_gophkeeper_v1_gophkeeper_proto_depIdxs = []int32{
	14, // 0: gophkeeper.v1.AuthResponse.expires_at:type_name -> google.protobuf.Timestamp
	14, // 1: gophkeeper.v1.ItemHeader.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: gophkeeper.v1.ItemHeader.updated_at:type_name -> google.protobuf.Timestamp
	14, // 3: gophkeeper.v1.ItemHeader.deleted_at:type_name -> google.protobuf.Timestamp
	9,  // 4: gophkeeper.v1.EncryptedItem.header:type_name -> gophkeeper.v1.ItemHeader
	9,  // 5: gophkeeper.v1.DeleteItemResponse.header:type_name -> gophkeeper.v1.ItemHeader
	10, // 6: gophkeeper.v1.ListItemsResponse.items:type_name -> gophkeeper.v1.EncryptedItem
	10, // 7: gophkeeper.v1.SyncResponse.items:type_name -> gophkeeper.v1.EncryptedItem
	0,  // 8: gophkeeper.v1.AuthService.Register:input_type -> gophkeeper.v1.RegisterRequest
	1,  // 9: gophkeeper.v1.AuthService.Login:input_type -> gophkeeper.v1.LoginRequest
	3,  // 10: gophkeeper.v1.VaultService.CreateItem:input_type -> gophkeeper.v1.CreateItemRequest
	4,  // 11: gophkeeper.v1.VaultService.UpdateItem:input_type -> gophkeeper.v1.UpdateItemRequest
	5,  // 12: gophkeeper.v1.VaultService.DeleteItem:input_type -> gophkeeper.v1.DeleteItemRequest
	6,  // 13: gophkeeper.v1.VaultService.GetItem:input_type -> gophkeeper.v1.GetItemRequest
	7,  // 14: gophkeeper.v1.VaultService.ListItems:input_type -> gophkeeper.v1.ListItemsRequest
	8,  // 15: gophkeeper.v1.VaultService.Sync:input_type -> gophkeeper.v1.SyncRequest
	2,  // 16: gophkeeper.v1.AuthService.Register:output_type -> gophkeeper.v1.AuthResponse
	2,  // 17: gophkeeper.v1.AuthService.Login:output_type -> gophkeeper.v1.AuthResponse
	9,  // 18: gophkeeper.v1.VaultService.CreateItem:output_type -> gophkeeper.v1.ItemHeader
	9,  // 19: gophkeeper.v1.VaultService.UpdateItem:output_type -> gophkeeper.v1.ItemHeader
	11, // 20: gophkeeper.v1.VaultService.DeleteItem:output_type -> gophkeeper.v1.DeleteItemResponse
	10, // 21: gophkeeper.v1.VaultService.GetItem:output_type -> gophkeeper.v1.EncryptedItem
	12, // 22: gophkeeper.v1.VaultService.ListItems:output_type -> gophkeeper.v1.ListItemsResponse
	13, // 23: gophkeeper.v1.VaultService.Sync:output_type -> gophkeeper.v1.SyncResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_gophkeeper_v1_gophkeeper_proto_init() }
func file_gophkeeper_v1_gophkeeper_proto_init() {
	if File_gophkeeper_v1_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_gophkeeper_proto_rawDesc), len(file_gophkeeper_v1_gophkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_gophkeeper_v1_gophkeeper_proto_goTypes,
		DependencyIndexes: file_gophkeeper_v1_gophkeeper_proto_depIdxs,
		MessageInfos:      file_gophkeeper_v1_gophkeeper_proto_msgTypes,
	}.Build()
	File_gophkeeper_v1_gophkeeper_proto = out.File
	file_gophkeeper_v1_gophkeeper_proto_goTypes = nil
	file_gophkeeper_v1_gophkeeper_proto_depIdxs = nil
}
